title: "Aamena Mahudhawala"
description: "Portfolio showcasing projects in Robotics, IoT, and AI"
theme: minima

# Navigation links
header_pages:
  - index.md
  - about.md
  - projects/index.md
  - contact.md
